core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('cryptocurrency.urls')),
    path('users/', include('users.urls')),
]

handler403 = 'cryptocurrency.views.handler403'
handler404 = 'cryptocurrency.views.handler404'
handler500 = 'cryptocurrency.views.handler500'

core/users/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView

from . import views

app_name = "users"
print(settings.STATIC_ROOT)
print(settings.STATIC_URL)
urlpatterns = [
    path('signup/', views.register, name='register'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         views.activate, name='activate'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/users/models.py
from cloudinary.forms import CloudinaryFileField
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AbstractUser):
    is_email_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.URLField(null=True, max_length=300)
    bio = models.CharField(default=None, null=True, max_length=500)

    def __str__(self):
        return str(self.avatar)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()


class Watchlist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favorites = ArrayField(models.IntegerField(max_length=10, null=True), blank=True, default=list)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Watchlist.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

core/users/forms.py
from cloudinary.forms import CloudinaryFileField
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import Profile

user = get_user_model()


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput({'class': 'form-control'}))
    last_name = forms.CharField(max_length=40, required=True, widget=forms.TextInput({'class': 'form-control'}))
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput({'class': 'form-control'}))
    email = forms.CharField(max_length=150, required=True, widget=forms.EmailInput({'class': 'form-control'}))
    password1 = forms.CharField(max_length=20, min_length=5, required=True,
                                widget=forms.PasswordInput({'class': 'form-control'}))
    password2 = forms.CharField(max_length=20, min_length=5, required=True,
                                widget=forms.PasswordInput({'class': 'form-control'}))

    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput({'class': 'form-control'}))
    password = forms.CharField(max_length=20, min_length=5, required=True,
                               widget=forms.PasswordInput({'class': 'form-control'}))

    class Meta:
        model = User
        fields = ["username", "password"]


class UserForm(RegisterForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email", "password1", "password2"]


class ProfileForm(forms.ModelForm):
    bio = forms.CharField(max_length=300, min_length=5, required=False,
                          widget=forms.Textarea({'class': 'form-control', 'rows': 4}), label='bio')

    class Meta:
        model = Profile
        fields = ["avatar", "bio"]


class PasswordChangeForm(forms.ModelForm):
    current_password = forms.CharField(max_length=20, min_length=5, required=True,
                                       widget=forms.PasswordInput({'class': 'form-control'}))
    new_password = forms.CharField(max_length=20, min_length=5, required=True,
                                   widget=forms.PasswordInput({'class': 'form-control'}))

    class Meta:
        model = User
        fields = ["current_password", "new_password"]


class UpdateAvatarFrom(forms.ModelForm):
    image = forms.ImageField()

    class Meta:
        model = Profile
        fields = ["avatar"]

core/users/views.py
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import cloudinary
from cloudinary.uploader import upload
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.hashers import check_password
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.template import RequestContext
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.conf import settings
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import TemplateView
from django.contrib.auth.hashers import make_password

from .forms import RegisterForm, LoginForm, ProfileForm, UserForm, PasswordChangeForm, UpdateAvatarFrom
from .models import User, Profile
from .tokens import account_activation_token


def send_email(message, to_email, ) -> None:
    with smtplib.SMTP_SSL(settings.EMAIL_HOST, settings.EMAIL_HOST_PORT) as server:
        try:
            from_email = settings.EMAIL_HOST_USER
            from_email_password = settings.EMAIL_HOST_PASSWORD
            server.login(from_email, from_email_password)
            msg = MIMEMultipart()
            msg['From'] = from_email
            msg['To'] = to_email
            msg['Subject'] = 'Confirm registration'

            msg.attach(MIMEText(message, 'html'))

            print(msg)
            server.send_message(msg)
        except Exception as err:
            print(err)


def activate(request, uidb64, token):
    user_model = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = user_model.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, user_model.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_email_verified = True
        user.save()
        return redirect(to="users:login")
    else:
        messages.error(request, 'Activation link is invalid! Try again')


def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if User.objects.filter(username=username).exists():
            messages.info(request, 'Username already exist')
            return redirect(to="users:register")
        elif User.objects.filter(email=email).exists():
            messages.info(request, 'Email is taken, choose another one')
            return redirect(to="users:register")
        else:
            if password1 == password2:
                user = User.objects.create_user(
                    first_name=first_name, last_name=last_name, username=username, email=email,
                    password=password1)
                user.save()
                current_site = get_current_site(request)
                message = render_to_string('users/activate_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                to_email = email
                send_email(message, to_email)
                messages.success(request, "Please confirm your email address to complete the registration")
            else:
                messages.error(request, "Passwords don't match")
    return render(request, 'users/register.html', {"form": form})


def login_user(request):
    form = LoginForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                if user.is_email_verified:
                    login(request, user)
                    return redirect(to='cryptocurrency:home')
                else:
                    messages.error(request, 'Please confirm your email to log in')
            else:
                messages.error(request, 'Your account is disabled')
        else:
            messages.error(request, 'Invalid username or password')

    return render(request, 'users/login.html', {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(to='cryptocurrency:home')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:login')
    # success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'users/profile.html'

    def post(self, request):
        post_data = request.POST or None
        file_data = request.FILES or None
        user = request.user
        profile = Profile.objects.get(user=user)

        if 'update_user' in request.POST:
            first_name = post_data.get("first_name")
            last_name = post_data.get("last_name")
            username = post_data.get("username")
            email = post_data.get("email")
            bio = post_data.get("bio")

            user.first_name = first_name
            user.last_name = last_name
            user.username = username
            user.email = email
            user.save()

            profile.bio = bio
            profile.save()
            user_updated_successfully = True
            if user_updated_successfully:
                messages.success(request, 'User information updated successfully!')
            else:
                messages.error(request, 'Failed to update user info.')
            return redirect(to='users:profile')

        if 'update_password' in request.POST:
            current_password = post_data.get('current_password')
            new_password = post_data.get('new_password')

            if check_password(current_password, user.password):
                hashed_new_password = make_password(new_password)
                user.password = hashed_new_password
                user.save()
                update_session_auth_hash(request, user)
                password_updated_successfully = True
                if password_updated_successfully:
                    messages.success(request, 'Password updated successfully!')
                else:
                    messages.error(request, 'Failed to update password.')
            else:
                messages.error(request, "Wrong password")
            return redirect(to='users:profile')

        if 'update_photo' in request.POST:
            username = user.username
            image_file = file_data.get('image')

            if image_file:
                cloudinary.config(
                    cloud_name=os.environ.get('CLOUDINARY_NAME'),
                    api_key=os.environ.get('CLOUDINARY_API_KEY'),
                    api_secret=os.environ.get('CLOUDINARY_API_SECRET'),
                    secure=True
                )

                r = cloudinary.uploader.upload(image_file, public_id=f'Crypto/{username}',
                                               overwrite=True)
                image_url = cloudinary.CloudinaryImage(f'Crypto/{username}') \
                    .build_url(width=150, height=150, crop='fill', version=r.get('version'))

                # Save the image URL to the user's profile or wherever you need to store it
                profile = Profile.objects.get(user=user)
                profile.avatar = image_url
                profile.save()

                photo_updated_successfully = True
                if photo_updated_successfully:
                    messages.success(request, 'Avatar updated successfully!')
                else:
                    messages.error(request, 'Failed to update Avatar')
            else:
                messages.error(request, 'Failed to get image')
            return redirect(to='users:profile')

    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=request.user.id)
        user_form = UserForm(instance=user)
        first_name = user.first_name
        last_name = user.last_name
        username = user.username

        profile = Profile.objects.get(user=request.user)
        bio = profile.bio
        initial_data = {
            'bio': bio
        }
        profile_form = ProfileForm(initial=initial_data)
        avatar_url = profile.avatar

        change_password_form = PasswordChangeForm()
        update_avatar = UpdateAvatarFrom()

        context = self.get_context_data(
            user_form=user_form,
            profile_form=profile_form,
            change_password_form=change_password_form,
            update_avatar=update_avatar,
            first_name=first_name,
            last_name=last_name,
            username=username,
            bio=bio,
            avatar=avatar_url
        )

        return self.render_to_response(context)

core/users/templates/users/activate_email.html
{% autoescape off %}
<html>
<head>
    <meta charset="utf-8">
    <title>Email Confirmation</title>
</head>
<body>
<p>Hi {{user.username}},</p>
<p>Thank you for signing up for our service.</p>
<p>Please click the following link to verify your email address:</p>
<p>
    <a href="http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}">
        Verification
    </a>
</p>
<p>If you did not sign up for our service, please ignore this email.</p>
<p>Regards,</p>
<p>CryptoAnalytics Team</p>
</body>
</html>
{% endautoescape %}

core/users/templates/users/activation_link_invalid.html
{% extends 'cryptocurrency/base.html' %}

{% block content %}

<p>Activation link is invalid!</p>

{% endblock %}

core/users/templates/users/login.html
{% extends 'cryptocurrency/base.html' %}

{% block content %}
{% load static %}

<div class="content">
    <div class="container">

        <div class="row pt-5">
            {% if messages %}
            <div class="messages" style="max-width: 50%; margin-right: 20px">
                {% for message in messages %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <div class="card" style="max-width: 60%">

                <form role="form" method="post">
                    {% csrf_token %}

                    <h4 class="title" style="text-align:center; margin-top:20px">
                        Sign IN
                    </h4>

                    <div class="card-body px-5 py-3">

                        <div class="row">
                            <div class="col-md-12 px-md-1">
                                <div class="form-group">
                                    <label>Username</label>
                                    {{ form.username }}
                                    {% if form.errors.username %}
                                    <div class="text-danger">
                                        {{ form.errors.username }}
                                    </div>
                                    {% endif %}
                                </div>
                            </div>


                            <div class="col-md-12 px-md-1">
                                <div class="form-group">
                                    <label>Password</label>
                                    {{ form.password }}
                                    {% if form.errors.password %}
                                    <div class="text-danger">
                                        {{ form.errors.password }}
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer text-center">
                        <a href="{% url 'users:password_reset' %}" class="text-center">Forgot Password?</a>
                    </div>
                    <div class="card-footer text-center">
                        <button type="submit" class="btn btn-fill btn-primary">Login</button>
                        <br>
                        <p>
                            Don't have an account? <a href="{% url 'users:register'%}"
                                                      class="text-primary">Register</a>
                        </p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

core/users/templates/users/password_reset.html
{% extends 'cryptocurrency/base.html' %}

{% block content %}
<div class="content">
    <div class="container">
        <div class="row pt-5">
            <div class="card" style="max-width: 60%">
                <form method="post">
                    {% csrf_token %}
                    <div class="card-body px-5 py-3">
                        <div class="row">
                            <div class="col-md-12 px-md-1">
                                <div class="form-group">
                                    <h4>Password reset</h4>
                                    {% if form.errors %}
                                        <div class="alert alert-danger" role="alert">
                                            {% for field in form %}
                                                {% if field.errors %}
                                                    <ul class="m-0">
                                                        {% for error in field.errors %}
                                                            <li>{{ error }}</li>
                                                        {% endfor %}
                                                    </ul>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                    {{ form.as_p }}
                                    <button type="submit" name="login" class="btn btn-fill btn-primary">Request password
                                        reset
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

core/users/templates/users/password_reset_complete.html
{% extends 'cryptocurrency/base.html' %}

{% block content %}

<div class="content">
    <div class="container">
        <div class="row pt-5">
            <div class="card" style="max-width: 60%">
                <div class="card-body px-5 py-3">

                    <div class="row">
                        <div class="col-md-12 px-md-1">
                            <div class="form-group">
                                <h4>Password reset complete</h4>
                                <hr>
                                <p>Your password has been set. You may go ahead and log in now.</p>
                                <a href="/users/login" class="btn btn-primary">Login</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

core/users/templates/users/password_reset_confirm.html
{% extends 'cryptocurrency/base.html' %}

{% block title %}Enter new password{% endblock %}

{% block content %}

{% if validlink %}
<style>
input[type=button], input[type=submit], input[type=reset] {
  background-color: blue;
  border: none;
  color: white;
  padding: 8px 16px;
  text-decoration: none;
  margin: 4px 2px;
  cursor: pointer;
  border-radius: 4px;
}


</style>
<div class="content">
    <div class="container">
        <div class="row pt-5">
            <div class="card" style="max-width: 60%">
                <h4 class="title" style="text-align:center; margin-top:20px">Set a new password!</h4>
                <form method="post">
                    <div class="card-body px-5 py-3">

                        <div class="row">
                            <div class="col-md-12 px-md-1">
                                <div class="form-group">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <input type="submit" value="Change my password">
                                </div>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
{% else %}

<p>The password reset link was invalid, possibly because it has already been used. Please request a new password
    reset.</p>

{% endif %}
{% endblock %}

core/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account on the CryptoAnalytics. Please follow the link to set a new
    password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        Reset password
    </a>
</p>
<p>If you didn't request a password reset, just ignore this email.</p>
<p>Thanks!</p>
{% endautoescape %}

core/users/templates/users/profile.html
{% extends 'cryptocurrency/base.html' %}

{% block content %}
{% load static %}

<div class="content">
    {% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
        <div class="messages alert-success">
            <ul>
                <li>{{ message }}</li>
            </ul>
        </div>
        {% elif message.tags == 'error' %}
        <div class="messages alert-danger">
            <ul>
                <li>{{ message }}</li>
            </ul>
        </div>
        {% endif %}
    {% endfor %}

    {% endif %}
    <div class="row">
        <div class="col-md-8" style="max-width:900px; margin-left: 20px">
            <div class="card">
                <div class="card-header">
                    <h4 class="title">Edit Profile</h4>
                </div>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4 pr-md-1">
                                <div class="form-group">
                                    <label>First Name</label>
                                    {{user_form.first_name}}
                                </div>
                            </div>
                            <div class="col-md-4 pl-md-1">
                                <div class="form-group">
                                    <label>Last Name</label>
                                    {{user_form.last_name}}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 pr-md-1">
                                <div class="form-group">
                                    <label>Username</label>
                                    {{user_form.username}}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 pr-md-1">
                                <div class="form-group">
                                    <label>Email address</label>
                                    {{user_form.email}}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>About Me</label>
                                    {{profile_form.bio}}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-fill btn-primary" name="update_user">Save</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-user">
                <div class="card-body">
                    <div class="author">
                        <div class="block block-one"></div>
                        <div class="block block-two"></div>
                        <div class="block block-three"></div>
                        <div class="block block-four"></div>
                        {% if avatar %}
                        <img src="{{ avatar }}" alt="Image" class="avatar">
                        {% else %}
                        <!-- Default avatar or placeholder image -->
                        <img src="{% static 'users/images/default-avatar.png' %}" alt="Default Avatar"
                             class="avatar">
                        {% endif %}
                        <h3 class="title">{{first_name}} {{last_name}}</h3>
                        <p class="description" style="margin-top:-20px;">
                            <b>{{username}}</b>
                        </p>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-description">
                            <p style="text-align:center;margin-top:-15px;color:rgba(234, 240, 246, 0.8);">Bio</p>
                            {% if bio %}
                            <p class="description" style="text-align:center">{{bio}}</p>
                            {% else %}
                            <p class="description" style="text-align:center">Your biography</p>
                            {% endif %}
                        </div>
                    </form>
                </div>
            </div>
            <div style="width: 300px">
                <div class="card card-user" style="max-height:200px">
                    <div class="card-body">
                        <h4 class="title" style="margin-bottom:4px">Change an avatar</h4>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="custom-file-upload">
                                {{update_avatar.image}}
                            </div>
                            <button type="submit" class="btn btn-fill btn-primary" name="update_photo">Upload</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8" style="max-width:900px; margin-left: 20px">
            <div class="card">
                <div class="card-header">
                    <h4 class="title">Change password</h4>
                </div>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4 pr-md-1">
                                <div class="form-group">
                                    <label>Current password</label>
                                    {{change_password_form.current_password}}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 pr-md-1">
                                <div class="form-group">
                                    <label>New password</label>
                                    {{change_password_form.new_password}}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-fill btn-primary" name="update_password">Change</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}