core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('cryptocurrency.urls')),
    path('users/', include('users.urls')),
]

handler403 = 'cryptocurrency.views.handler403'
handler404 = 'cryptocurrency.views.handler404'
handler500 = 'cryptocurrency.views.handler500'

core/cryptocurrency/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from . import views

app_name = 'cryptocurrency'

print(settings.STATIC_ROOT)
urlpatterns = [
                  path('', views.home, name='home'),
                  path('rates/', views.rates, name='rates'),
                  path('rates/load_all/', views.load_more, name='load_more'),
                  path('rates/update/', views.update_rates, name='update_rates'),
                  path('rates/download/', views.download_file, name='download'),

                  path('search/', views.search_field, name='search_field'),

                  path('news/', views.news, name='news'),
                  path('news/<int:page>/', views.news, name='root_paginate'),
                  path('news/update/', views.update_news, name='update_news'),

                  path('watchlist/', views.watchlist, name='watchlist'),
                  path('watchlist/download/', views.download_file_watchlist, name='download_watchlist'),

                  path('user-dropdown/', views.user_dropdown, name='user-dropdown'),

                  path('rates/price-filter/ascend', views.Filter.filter_by_price_ascend,
                       name='filter_by_price_ascend'),
                  path('rates/price-filter/descend', views.Filter.filter_by_price_descend,
                       name='filter_by_price_descend'),
                  path('rates/change1h-filter/ascend', views.Filter.filter_by_change1h_ascend,
                       name='filter_by_change1h_ascend'),
                  path('rates/change1h-filter/descend', views.Filter.filter_by_change1h_descend,
                       name='filter_by_change1h_descend'),
                  path('rates/change24h-filter/ascend', views.Filter.filter_by_change24h_ascend,
                       name='filter_by_change24h_ascend'),
                  path('rates/change24h-filter/descend', views.Filter.filter_by_change24h_descend,
                       name='filter_by_change24h_descend'),
                  path('rates/change7d-filter/ascend', views.Filter.filter_by_change7d_ascend,
                       name='filter_by_change7d_ascend'),
                  path('rates/change7d-filter/descend', views.Filter.filter_by_change7d_descend,
                       name='filter_by_change7d_descend'),
                  path('rates/supply-filter/ascend', views.Filter.filter_by_supply_ascend,
                       name='filter_by_supply_ascend'),
                  path('rates/supply-filter/descend', views.Filter.filter_by_supply_descend,
                       name='filter_by_supply_descend'),
                  path('rates/id-filter/ascend', views.Filter.filter_by_id_ascend,
                       name='filter_by_id_ascend'),
                  path('rates/id-filter/descend', views.Filter.filter_by_id_descend,
                       name='filter_by_id_descend'),
                  path('rates/name-filter/ascend', views.Filter.filter_by_name_ascend,
                       name='filter_by_name_ascend'),
                  path('rates/name-filter/descend', views.Filter.filter_by_name_descend,
                       name='filter_by_name_descend'),
                  path('rates/symbol-filter/ascend', views.Filter.filter_by_symbol_ascend,
                       name='filter_by_symbol_ascend'),
                  path('rates/symbol-filter/descend', views.Filter.filter_by_symbol_descend,
                       name='filter_by_symbol_descend'),
                  path('rates/coin_id-filter/ascend', views.Filter.filter_by_coin_id_ascend,
                       name='filter_by_coin_id_ascend'),
                  path('rates/coin_id-filter/descend', views.Filter.filter_by_coin_id_descend,
                       name='filter_by_coin_id_descend'),

                  path('watchlist/price-filter/ascend', views.FilterWatchlist.filter_by_price_ascend,
                       name='watchlist_filter_by_price_ascend'),
                  path('watchlist/price-filter/descend', views.FilterWatchlist.filter_by_price_descend,
                       name='watchlist_filter_by_price_descend'),
                  path('watchlist/change1h-filter/ascend', views.FilterWatchlist.filter_by_change1h_ascend,
                       name='watchlist_filter_by_change1h_ascend'),
                  path('watchlist/change1h-filter/descend', views.FilterWatchlist.filter_by_change1h_descend,
                       name='watchlist_filter_by_change1h_descend'),
                  path('watchlist/change24h-filter/ascend', views.FilterWatchlist.filter_by_change24h_ascend,
                       name='watchlist_filter_by_change24h_ascend'),
                  path('watchlist/change24h-filter/descend', views.FilterWatchlist.filter_by_change24h_descend,
                       name='watchlist_filter_by_change24h_descend'),
                  path('watchlist/change7d-filter/ascend', views.FilterWatchlist.filter_by_change7d_ascend,
                       name='watchlist_filter_by_change7d_ascend'),
                  path('watchlist/change7d-filter/descend', views.FilterWatchlist.filter_by_change7d_descend,
                       name='watchlist_filter_by_change7d_descend'),
                  path('watchlist/supply-filter/ascend', views.FilterWatchlist.filter_by_supply_ascend,
                       name='watchlist_filter_by_supply_ascend'),
                  path('watchlist/supply-filter/descend', views.FilterWatchlist.filter_by_supply_descend,
                       name='watchlist_filter_by_supply_descend'),
                  path('watchlist/id-filter/ascend', views.FilterWatchlist.filter_by_id_ascend,
                       name='watchlist_filter_by_id_ascend'),
                  path('watchlist/id-filter/descend', views.FilterWatchlist.filter_by_id_descend,
                       name='watchlist_filter_by_id_descend'),
                  path('watchlist/name-filter/ascend', views.FilterWatchlist.filter_by_name_ascend,
                       name='watchlist_filter_by_name_ascend'),
                  path('watchlist/name-filter/descend', views.FilterWatchlist.filter_by_name_descend,
                       name='watchlist_filter_by_name_descend'),
                  path('watchlist/symbol-filter/ascend', views.FilterWatchlist.filter_by_symbol_ascend,
                       name='watchlist_filter_by_symbol_ascend'),
                  path('watchlist/symbol-filter/descend', views.FilterWatchlist.filter_by_symbol_descend,
                       name='watchlist_filter_by_symbol_descend'),
                  path('watchlist/coin_id-filter/ascend', views.FilterWatchlist.filter_by_coin_id_ascend,
                       name='watchlist_filter_by_coin_id_ascend'),
                  path('watchlist/coin_id-filter/descend', views.FilterWatchlist.filter_by_coin_id_descend,
                       name='watchlist_filter_by_coin_id_descend'),
              ] + static(settings.STATIC_URL)

core/users/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView

from . import views

app_name = "users"
print(settings.STATIC_ROOT)
print(settings.STATIC_URL)
urlpatterns = [
    path('signup/', views.register, name='register'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         views.activate, name='activate'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/cryptocurrency/models.py
from django.db import models


class Crypto(models.Model):
    coin_id = models.BigIntegerField(unique=True)
    name = models.CharField(max_length=100)
    symbol = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    percent_change_1h = models.DecimalField(max_digits=10, decimal_places=4)
    percent_change_24h = models.DecimalField(max_digits=10, decimal_places=4)
    percent_change_7d = models.DecimalField(max_digits=10, decimal_places=4)
    circulating_supply = models.BigIntegerField()


class News(models.Model):
    title = models.TextField()
    text = models.TextField()
    date = models.CharField()
    source = models.CharField()
    link = models.TextField()

core/cryptocurrency/forms.py
from django.forms import ModelForm, ModelChoiceField, Select
from django import forms


# class SearchForm(ModelForm):
#     search_by = ModelChoiceField(queryset=["coin", "news"], required=True, widget=Select())
#
#     class Meta:
#         fields = ['search_by']


class UserDropdownForm(forms.Form):
    OPTIONS = (
        ('profile', 'Profile'),
        ('logout', 'Logout'),
    )
    my_dropdown = forms.ChoiceField(choices=OPTIONS)

core/cryptocurrency/templates/cryptocurrency/back_to_rates.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/x-icon" href="{% static 'cryptocurrency/images/site-logo.png' %}">

    <title>
        CryptoAnalytics
    </title>

    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet"/>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'cryptocurrency/css/black-dashboard.css' %}"/>
</head>
<body>
<div class="content">
    <div class="container">
        <div class="row pt-5">
            <div class="col-md-6 mt-5 offset-md-3 pt-5 mt-5">
                <div class="card">
                    <div class="card-header text-center py-4">
                        <h3 class="title">
                            Sorry for unconvinience
                        </h3>
                    </div>
                    <div class="card-body px-2 py-2">

                        <p class="text-center">
                            Access denied - Please contact support.
                        </p>

                    </div>
                    <div class="card-footer text-center">
                        <a href="{% url 'cryptocurrency:home' %}" class="btn btn-fill btn-primary">HOME</a>

                        <br/><br/>

                        <p>
                            Write to us at gmail (andriy.svitelskyi@gmail.com) to get support
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>
</body>
</html>

core/cryptocurrency/templates/cryptocurrency/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/x-icon" href="{% static 'cryptocurrency/images/site-logo.png' %}">

    <title>
        CryptoAnalytics
    </title>

    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet"/>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'cryptocurrency/css/style.css' %}"/>

    <!-- JS Files -->
    <script src="{% static 'cryptocurrency/js/messages.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'cryptocurrency/js/watchlist.js' %}"></script>
    <script src="{% static 'cryptocurrency/js/dropdown.js' %}"></script>
    <script src="{% static 'cryptocurrency/js/update_page.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


</head>
<body>

<div class="wrapper">
    <div class="sidebar">
        <div class="sidebar-wrapper">
            <div class="logo">
                <img src="{% static 'cryptocurrency/images/logo.png' %}">
            </div>
            <ul class="nav">
                <li>
                    <a href="{% url 'cryptocurrency:home' %}" class="menu-link">
                        <img src="{% static 'cryptocurrency/images/dashboard.png' %}">
                        <h4>Dashboard</h4>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cryptocurrency:rates' %}" class="menu-link">
                        <img src="{% static 'cryptocurrency/images/crypto.png' %}">
                        <h4>Cryptocurrencies</h4>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cryptocurrency:news' %}" class="menu-link">
                        <img src="{% static 'cryptocurrency/images/news.png' %}">
                        <h4>News</h4>
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'cryptocurrency:watchlist' %}" class="menu-link">
                        <img src="{% static 'cryptocurrency/images/star-uncolored.png' %}">
                        <h4>Watchlist</h4>
                    </a>
                </li>
                <li>
                    <a href="{% url 'users:profile' %}" class="menu-link">
                        <img src="{% static 'cryptocurrency/images/user.png' %}"
                             style="width:32px;height:32px;float:left;">
                        <h4 style="margin:0px;height:32px;max-width:100%;float:left;overflow:auto;">User Profile</h4>
                    </a>
                </li>
                {% endif %}
            </ul>
            <div class="sidebar-icons">
                <a href="https://www.linkedin.com/in/andrii-svitelskyi-2a4775262/"><img
                        src="{% static 'cryptocurrency/images/linkedin.png' %}"></a>
                <a href="https://github.com/AndriiSeeker"><img
                        src="{% static 'cryptocurrency/images/github.png' %}"></a>
                <a href="https://t.me/CryptoCurrencyPetBot"><img
                        src="{% static 'cryptocurrency/images/telegram.png' %}"></a>
            </div>
        </div>
    </div>
    <div class="main-panel">

        <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
            <div class="container-fluid">
                <div class="navbar-wrapper">
                    <a class="navbar-brand" href="{% url 'cryptocurrency:home' %}" style="font-size: 20px">CryptoAnalytics</a>
                </div>
                {% if user.is_authenticated %}
                <div class="collapse navbar-collapse" id="navigation">
                    <ul class="navbar-nav ml-auto">
                        <li>
                            <form action="{% url 'cryptocurrency:search_field' %}" method="get" class="search-form">
                                <input type="text" name="query" class="search-input" placeholder="Search..."/>
                                <button type="submit" class="search-button">
                                    <svg class="search-icon" viewBox="0 0 24 24">
                                        <path d="M15.5 14h-.79l-.28-.27a6.47 6.47 0 1 0-.7.7l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-4 0A4.5 4.5 0 1 1 14 9.5a4.47 4.47 0 0 1-4.5 4.5z"/>
                                    </svg>
                                </button>
                            </form>
                        </li>
                        <li class="dropdown nav-item">
                            <a href="{% url 'users:profile' %}" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                <div class="photo">
                                    {% if avatar %}
                                    <img src="{{ avatar }}" alt="Image" class="avatar">
                                    {% else %}
                                    <!-- Default avatar or placeholder image -->
                                    <img src="{% static 'users/images/default-avatar.png' %}" alt="Default Avatar"
                                         class="avatar">
                                    {% endif %}
                                </div>
                            </a>
                        </li>
                    </ul>

                    <div class="user-dropdown">
                        <button onclick="myFunction()" class="dropbtn" id="dropbtn"><img
                                src="{% static 'cryptocurrency/images/sort-down.png' %}"></button>
                        <div id="myDropdown" class="dropdown-content">
                            <a href="{% url 'users:profile' %}">My profile</a>
                            <a href="{% url 'users:logout' %}">Logout</a>
                        </div>
                    </div>

                </div>
                {% else %}
                <div class="collapse navbar-collapse" id="navigation">
                    <ul class="navbar-nav ml-auto">
                        <li class="search-bar input-group">
                            <a href="/users/signup">
                                <button type="submit" class="btn btn-fill btn-primary">Signup</button>
                            </a>
                        </li>
                        <li class="search-bar input-group">
                            <a href="{% url 'users:login' %}">
                                <button type="submit" class="btn btn-fill btn-primary">Login</button>
                            </a>
                        </li>
                    </ul>
                </div>
                {% endif %}
            </div>
        </nav>

        {% block content %}{% endblock %}

        <footer class="footer">
            <div class="container-fluid">
                <div class="copyright">
                    &copy; Made by <a target="_blank" href="https://www.linkedin.com/in/andrii-svitelskyi-2a4775262/">Andrii
                    Svitelskyi</a>
                </div>
            </div>
        </footer>

    </div>
</div>

</body>
</html>

core/cryptocurrency/templates/cryptocurrency/crypto_rates.html
{% extends 'cryptocurrency/base.html' %}

{% block content %}
{% load static %}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card ">
                <div class="card-header">
                    <h3 class="card-title">Today's Cryptocurrency Prices</h3>

                    <div class="btn-container">
                        <div class="btn-group btn-group-toggle float-right" data-toggle="buttons"
                             style="margin-left:20px">
                            <form action="{% url 'cryptocurrency:update_rates' %}" method="post" id="update-rates-form">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success">Update</button>
                            </form>
                        </div>

                        <div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
                            <a href="{% url 'cryptocurrency:download' %}" id="export-rates">
                                <button type="submit" class="btn btn-success">Export</button>
                            </a>
                        </div>
                    </div>
                </div>


                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table tablesorter " id="">
                            <thead class=" text-primary">
                            <tr>
                                {% if user.is_authenticated %}
                                <th>

                                </th>
                                {% endif %}
                                <th style="max-width:30px">
                                    #
                                    <a href="{% url 'cryptocurrency:filter_by_id_ascend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-up.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                    <a href="{% url 'cryptocurrency:filter_by_id_descend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-down.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                </th>
                                <th>
                                    Name
                                    <a href="{% url 'cryptocurrency:filter_by_name_ascend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-up.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                    <a href="{% url 'cryptocurrency:filter_by_name_descend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-down.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                </th>
                                <th style="max-width:60px">
                                    Symbol
                                    <a href="{% url 'cryptocurrency:filter_by_symbol_ascend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-up.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                    <a href="{% url 'cryptocurrency:filter_by_symbol_descend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-down.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                </th>
                                <th style="max-width:50px">
                                    Price
                                    <a href="{% url 'cryptocurrency:filter_by_price_ascend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-up.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                    <a href="{% url 'cryptocurrency:filter_by_price_descend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-down.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                </th>
                                <th class="text-center">
                                    1h %
                                    <a href="{% url 'cryptocurrency:filter_by_change1h_ascend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-up.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                    <a href="{% url 'cryptocurrency:filter_by_change1h_descend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-down.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                </th>
                                <th class="text-center">
                                    24h %
                                    <a href="{% url 'cryptocurrency:filter_by_change24h_ascend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-up.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                    <a href="{% url 'cryptocurrency:filter_by_change24h_descend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-down.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                </th>
                                <th class="text-center">
                                    7d %
                                    <a href="{% url 'cryptocurrency:filter_by_change7d_ascend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-up.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                    <a href="{% url 'cryptocurrency:filter_by_change7d_descend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-down.png' %}"
                                            style="width: 17px;height: auto; font-size:10px"/></a>
                                </th>
                                <th class="text-center">
                                    Circulating supply
                                    <a href="{% url 'cryptocurrency:filter_by_supply_ascend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-up.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                    <a href="{% url 'cryptocurrency:filter_by_supply_descend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-down.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                </th>
                                <th class="text-center">
                                    Coin id
                                    <a href="{% url 'cryptocurrency:filter_by_coin_id_ascend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-up.png' %}"
                                            style="width: 17px;height: auto;"/></a>
                                    <a href="{% url 'cryptocurrency:filter_by_coin_id_descend' %}"><img
                                            src="{% static 'cryptocurrency/images/arrow-down.png' %}"
                                            style="width: 17px  ;height: auto;"/></a>
                                </th>
                            </tr>
                            </thead>
                            {% if coins %}
                            {% for coin in coins %}
                            <tbody>
                            <tr>
                                {% if user.is_authenticated %}
                                <td>
                                    <form method="post" action="{% url 'cryptocurrency:rates' %}" class="favorite-form"
                                          style="width: 25px">
                                        {% csrf_token %}
                                        <input type="hidden" name="coin_id" value="{{ coin.id }}">
                                        {% if coin.id in favorites %}
                                        <button class="star-icon colored" type="submit" data-coin-id="{{ coin.id }}">
                                            <img src="{% static 'cryptocurrency/images/star-colored.png' %}"
                                                 alt="Colored Star" class="star-favorite">
                                        </button>
                                        {% else %}
                                        <button class="star-icon" type="submit" data-coin-id="{{ coin.id }}">
                                            <img src="{% static 'cryptocurrency/images/star-uncolored.png' %}"
                                                 alt="Uncolored Star" class="star-favorite">
                                        </button>
                                        {% endif %}
                                    </form>
                                </td>
                                {% endif %}
                                <td style="max-width:30px">
                                    {{ coin.id }}
                                </td>
                                <td>
                                    {{ coin.name }}
                                </td>
                                <td style="max-width:60px">
                                    {{ coin.symbol }}
                                </td>
                                <td style="max-width:50px">
                                    {{ coin.price }}
                                </td>
                                <td class="text-center">
                                    {% if coin.percent_change_1h < 0%}
                                    <a style="color:red">{{ coin.percent_change_1h }}</a>
                                    {%else %}
                                    <a style="color:green">{{ coin.percent_change_1h }}</a>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if coin.percent_change_24h < 0 %}
                                    <a style="color:red">{{ coin.percent_change_24h }}</a>
                                    {%else %}
                                    <a style="color:green">{{ coin.percent_change_24h }}</a>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if coin.percent_change_7d < 0 %}
                                    <a style="color:red">{{ coin.percent_change_7d }}</a>
                                    {%else %}
                                    <a style="color:green">{{ coin.percent_change_7d }}</a>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {{ coin.circulating_supply }}
                                </td>
                                <td class="text-center">
                                    {{ coin.coin_id }}
                                </td>
                            </tr>
                            </tbody>
                            {% endfor %}
                            {% endif %}
                        </table>
                        {% if coins|length == 15%}
                        <div style="text-align: center">
                            <a href="{% url 'cryptocurrency:load_more' %}" class="btn btn-light">Load all</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}